-- auto Generated on 2018-11-10 21:10:30 
-- DROP TABLE IF EXISTS `diary`; 
CREATE TABLE diary(
    `id` INTEGER(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
    `diary_id` INTEGER(12) NOT NULL DEFAULT -1 COMMENT 'diaryId',
    `user_id` INTEGER(12) NOT NULL DEFAULT -1 COMMENT 'userId',
    `diary_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'diaryName',
    `diary_text` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'diaryText',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'createTime',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updateTime',
    `is_deleted` INTEGER(12) NOT NULL DEFAULT -1 COMMENT 'isDeleted',
    PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'diary';
