-- auto Generated on 2018-11-10 21:10:38 
-- DROP TABLE IF EXISTS `image`; 
CREATE TABLE image(
    `id` INTEGER(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
    `user_id` INTEGER(12) NOT NULL DEFAULT -1 COMMENT 'userId',
    `class_id` INTEGER(12) NOT NULL DEFAULT -1 COMMENT 'classId',
    `image_name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'imageName',
    `image_text` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'imageText',
    `image_path` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'imagePath',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'createTime',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updateTime',
    `is_deleted`  TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'isDeleted',
    PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'image';
