-- auto Generated on 2018-11-10 21:11:09 
-- DROP TABLE IF EXISTS `user_icon`; 
CREATE TABLE user_icon(
    `id` INTEGER(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
    `user_id` INTEGER(12) NOT NULL DEFAULT -1 COMMENT 'userId',
    `icon_path` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'iconPath',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'createTime',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'updateTime',
    `is_deleted` INTEGER(12) NOT NULL DEFAULT -1 COMMENT 'isDeleted',
    PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'user_icon';
